---
title: "期末競賽"
author: "第 9 組"
date: "`r Sys.time()`"
output:
  html_document:
    highlight: pygments
    theme: flatly
    css: style.css
---


```{r}
library(dplyr)
library(ggplot2)
library(caTools)
library(ROCR)
library(googleVis)
library(chorddiag)
library(readr)

x <- read_csv("data/ta_feng_all_months_merged.csv")
load("group9.rdata")

```


```{r}
MRG = 0.5
### 
colnames(A)[1] <- "cust"
customer <- left_join(customer, A[,c(1,10,11,12)],  by = "cust")
C <- customer 
```

以`35-39`為行銷對象
```{r}
A2 = subset(A, AGEGROUP == "35-39")
P0=C$Buy
R0=C$Rev
```


```{r}
cost = 5
k1 = 0.75 # fix effect on the probability of retaintion
```

+ 回購機率增額： $\Delta P_{ret} = k_1 - P_{retain}$
+ 淨期望報酬： $\pi = m \cdot R_{exp} \cdot \Delta P_{ret} - c$

```{r fig.height=2.4, fig.width=7.2}
par(mar=c(4,3,3,2), cex=0.8)
PI = R0*MRG*(k1 - P0) - cost
hist(PI, xlim=c(-50, 500), breaks=seq(-14000,8000,5), main="淨期望報償分布(R2)")
```

##### 修正：行銷工具不應該會有負的回購機率效果

+ $\Delta P_{ret} = max[0, k_1 - P_{retain}]$

```{r fig.height=2.4, fig.width=7.2}
par(mar=c(4,3,3,2), cex=0.8)
PI = R0*MRG*pmax(0, k1 - P0) - cost
hist(PI, breaks=seq(-10,8000,5),main="淨期望報償分布(R2)")
### hist(PI, xlim=c(-50, 50), breaks=seq(-500,500,5),main="淨期望報償分布(R2)")
```

##### 假設二：固定成本、增加回購機率($k_2$)

$$\Delta P_{ret} = \left\{\begin{matrix}
k_2 & P_{retain}<=1-k_2 \\ 
1-P_{retain} & else 
\end{matrix}\right.$$

```{r fig.height=2.4, fig.width=7.2}
k2 = 0.15  # max. incremental effect of instrument
cost = 5
par(mar=c(4,3,3,2), cex=0.8)
PI = MRG * R0 * ifelse(P0<=(1-k2), k2, 1-P0) - cost
hist(PI, breaks=seq(-10,1765,5),main="淨期望報償分布(R2)")
```

##### 計算工具在各族群的效益
```{r}
C = C %>% mutate(
  PI = MRG*Rev*ifelse(Buy<=(1-k2), k2, 1-Buy) - cost
  ) 
C %>% group_by(AGEGROUP.y) %>% 
  summarise(
    Group.Sz = n(),
    No.Target = sum(PI>0),
    AvgROI = mean(PI[PI>0]),
    TotalROI = sum(PI[PI>0])) %>% 
  arrange(No.Target) %>% 
  data.frame
```

##### 工具在各族群的淨期望報償分布
```{r fig.height=8, fig.width=7}
par(mfrow=c(5,2), mar=c(4,3,3,2), cex=0.8)
for(s in c("<25","25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64",">65")) {
  hist(C$PI[C$AGEGROUP.y==s], breaks=seq(-10,1800,20),
       ylim=c(0, 2000), main=s, xlab="exp.profit")
  abline(v=0, col='green', lty=2)}
```
<br><hr>

### 模擬成本與效果的關係

##### 帶有參數的函數
```{r}
m=0.20; a=20; b=15
curve(m*plogis((10/a)*(x-b)), 0, 30, lwd=2, ylim=c(0, 0.25))
abline(h=seq(0,0.2,0.05),v=seq(0,30,5),col='lightgrey',lty=2)
```

$$k_0=f(x)=m \cdot Logis[10(x - b)/a]$$

##### 使用`manipulate`套件做模擬
`manipulate()`不能在Rmd直接執行，需要另外開一個R窗格，把以下程式碼Copy過去跑
```{r eval=F}
manipulate({
  curve(m*plogis((10/a)*(x-b)), 0, 30, lwd=2, ylim=c(0, 0.25),
        main = TeX('$m \\cdot Logis(10(x - b)/a)$'), ylab="f(x)")
  abline(h=seq(0,0.2,0.05),v=seq(0,30,5),col='lightgrey',lty=2)
},
m = slider(0.05, 0.25,  0.20, step=0.01),
a = slider(  10,   30,    20, step=1),
b = slider(   4,   20,    15, step=1)
) 
```


##### 使用模擬方法找到最佳策略(參數)
```{r}
m=0.20; a=20; b=15
do.call(rbind, lapply(seq(5,40,0.5), function(c){
  p = m*plogis((10/a)*(c-b))
  C %>% mutate(
    PI = ifelse(Buy<=(1-p), p, 1-Buy) * Rev - c
  ) %>%
    group_by(AGEGROUP.y) %>% summarise(
      Cost = c,
      Group.Sz = n(),
      No.Target = sum(PI>0),
      AvgROI = mean(PI[PI>0]),
      TotalROI = sum(PI[PI>0])
    ) } ) ) %>% 
  ggplot(aes(x=Cost, y=TotalROI, col=AGEGROUP.y)) +
  geom_line(size=1.2) +
  ggtitle("Cost Effeciency per Segment ")
```


```{r}
C = C %>% mutate(
  PI = MRG*Rev*ifelse(Buy<=(1-k2), k2, 1-Buy) - cost
  ) 
C %>% group_by(week) %>% 
  summarise(
    Group.Sz = n(),
    No.Target = sum(PI>0),
    AvgROI = mean(PI[PI>0]),
    TotalROI = sum(PI[PI>0])) %>% 
  arrange(No.Target) %>% 
  data.frame
```

```{r}
m=0.20; a=20; b=15
do.call(rbind, lapply(seq(5,40,0.5), function(c){
  p = m*plogis((10/a)*(c-b))
  C %>% mutate(
    PI = ifelse(Buy<=(1-p), p, 1-Buy) * Rev - c
  ) %>%
    group_by(week) %>% summarise(
      Cost = c,
      Group.Sz = n(),
      No.Target = sum(PI>0),
      AvgROI = mean(PI[PI>0]),
      TotalROI = sum(PI[PI>0])
    ) } ) ) %>% 
  ggplot(aes(x=Cost, y=TotalROI, col=week)) +
  geom_line(size=1.2) +
  ggtitle("Cost Effeciency per Segment ")
```


```{r}
C = C %>% mutate(
  PI = MRG*Rev*ifelse(Buy<=(1-k2), k2, 1-Buy) - cost
  ) 
C %>% group_by(group.x) %>% 
  summarise(
    Group.Sz = n(),
    No.Target = sum(PI>0),
    AvgROI = mean(PI[PI>0]),
    TotalROI = sum(PI[PI>0])) %>% 
  arrange(No.Target) %>% 
  data.frame
```

```{r}
m=0.20; a=20; b=15
do.call(rbind, lapply(seq(5,40,0.5), function(c){
  p = m*plogis((10/a)*(c-b))
  C %>% mutate(
    PI = ifelse(Buy<=(1-p), p, 1-Buy) * Rev - c
  ) %>%
    group_by(group.x) %>% summarise(
      Cost = c,
      Group.Sz = n(),
      No.Target = sum(PI>0),
      AvgROI = mean(PI[PI>0]),
      TotalROI = sum(PI[PI>0])
    ) } ) ) %>% 
  ggplot(aes(x=Cost, y=TotalROI, col=group.x)) +
  geom_line(size=1.2) +
  ggtitle("Cost Effeciency per Segment ") + theme(text = element_text(family = "FZLTXHB--B51-0"))
```

